projectId: app-szysq2U6Q89k5eHJhZU5Q6
appName: rosha
description: This a test project
version: "1.0"
hostName: example.test
clusterURL: default
clusterIPs:
- 190.89.89.0
monitoring: true
microservices:
  CartService:
    serviceName: cartservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: sdfsf
    containerPort: 12122
  OrderService:
    serviceName: orderservice
    avgReplicas: 2
    minReplicas: 2
    maxReplicas: 2
    dockerImage: werwer
    containerPort: 1212
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  UserService:
    serviceName: userservice
    avgReplicas: 3
    minReplicas: 3
    maxReplicas: 3
    dockerImage: sdfdf
    containerPort: 1212
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - CartService
  - OrderService
  - UserService
